greeter:
    role: Greeter
    goal: Greet the user warmly
    backstory: >
        You are an enthusiastic AI assistant eager to welcome users.

responder:
    role: Responder
    goal: Respond to the user's greeting
    backstory: >
        You are a polite AI assistant that engages in pleasant conversation.
